#pragma once
namespace muranbase{
	enum WAITING_STATUS{ // the
		WS_NO_TOUCH, // Not belong to the waitor, but used when scanning the waitor.
		WS_WAITING,

		WS_TIMEOUT_TRYING,
		WS_FAILOUT_TRYING,
		//WS_COMPLETED,
		WS_COMPLETED_WAIT_BAD,
		WS_COMPLETED_BAD,
		WS_COMPLETED_OK,
	};

	enum FILE_OPEN_MODE{
		FILE_OPEN_MODE_NONE       = 0,
		FILE_OPEN_OPEN_FAILED,
		FILE_OPEN_CLOSED,
		FILE_OPEN_CLOSE_FAILED,
		FILE_OPEN_MODE_R,
		FILE_OPEN_MODE_W,
		FILE_OPEN_MODE_A,
		FILE_OPEN_MODE_RPLUS,
		FILE_OPEN_MODE_WPLUS,
		FILE_OPEN_MODE_APLUS,
	};


	enum CONNECTION_STATUS{
		CONN_STAT_NOT_SET,
		CONN_STAT_CONNECTED,
		CONN_STAT_LOGON,
		CONN_STAT_LOGOUT,
		CONN_STAT_DISCONNECTED,
	};

	inline const char* toCStrConnStat(CONNECTION_STATUS s){
		switch(s){
		case CONN_STAT_NOT_SET:
			return "未设";
			break;
		case CONN_STAT_CONNECTED:
			return "连接";
		case CONN_STAT_LOGON:
			return "登陆";
		case CONN_STAT_LOGOUT:
			return "退出";
		case CONN_STAT_DISCONNECTED:
		default:
			return "断开";
		}
	}


	enum INIT_STATE{
		INIT_NOT_SET = 0,
		INIT_DOING,
		INIT_OK,
		INIT_FAILED,
	};

	enum RSLT_LOAD_OBJ{
		RSLT_LOAD_OBJ_SUCCESS,
		RSLT_LOAD_OBJ_FAILED_NO_FILE,
		RSLT_LOAD_OBJ_FAILED_END_OF_FILE,
		RSLT_LOAD_OBJ_FAILED_SHORT_DATA,
		RSLT_LOAD_OBJ_FAILED_FILE_EXCEPTION,
		RSLT_LOAD_OBJ_FAILED_SHORT_MEMORY,
	};

	enum RSLT_INSERT_OBJ{
		RSLT_INSERT_OBJ_NO_TOUCH = 0,
		RSLT_INSERT_OBJ_SUCCESS,
		RSLT_INSERT_OBJ_SUCCESS_REPLACE,
		RSLT_INSERT_OBJ_SUCCESS_COPY,
		RSLT_INSERT_OBJ_FAILED_DUPLICATE,
		RSLT_INSERT_OBJ_FAILED_SHORT_RES,
		RSLT_INSERT_OBJ_FAILED_BAD_DATA,     // Data Content Error
		RSLT_INSERT_OBJ_FAILED_BAD_SEQUENCE, // Like Time Sequence
	};

	enum PARAMETER_PRIMITIVE_TYP{
		PARAMETER_PRIMITIVE_TYP_INT,
		PARAMETER_PRIMITIVE_TYP_INT64,
		PARAMETER_PRIMITIVE_TYP_DOUBLE,
		PARAMETER_PRIMITIVE_TYP_STRING,
		PARAMETER_PRIMITIVE_TYP_CHARBUF,
		PARAMETER_PRIMITIVE_TYP_CHAR_PtrPtr,
	};

}

enum MARKET_TIME_VERSION{
	MARKET_TIME_VERSION_1 = 1,
	MARKET_TIME_VERSION_2 = 2,
};